import 'package:go_router/go_router.dart';

/// 发现域路由 (发现页子页面)
/// 由 discovery 模块的屏幕填充
final List<GoRoute> discoveryRoutes = [
  // 以下路由由各屏幕实现后注册:
  // GoRoute(path: '/calendar', builder: (_, _) => const CalendarScreen()),
  // GoRoute(path: '/search', builder: (_, _) => const SearchScreen()),
  // GoRoute(path: '/rank', builder: (_, _) => const RankScreen()),
  // GoRoute(path: '/anime', builder: (_, _) => const AnimeScreen()),
  // GoRoute(path: '/staff', builder: (_, _) => const StaffScreen()),
  // GoRoute(path: '/catalog', builder: (_, _) => const CatalogScreen()),
  // GoRoute(path: '/catalog/:id', builder: (_, _) => const CatalogDetailScreen()),
  // GoRoute(path: '/yearbook', builder: (_, _) => const YearbookScreen()),
  // GoRoute(path: '/tags', builder: (_, _) => const TagsScreen()),
  // GoRoute(path: '/blogs', builder: (_, _) => const BlogsScreen()),
  // GoRoute(path: '/groups', builder: (_, _) => const GroupsScreen()),
  // GoRoute(path: '/series', builder: (_, _) => const SeriesScreen()),
  // GoRoute(path: '/recommend', builder: (_, _) => const RecommendScreen()),
  // GoRoute(path: '/like', builder: (_, _) => const LikeScreen()),
  // GoRoute(path: '/pic', builder: (_, _) => const PicScreen()),
  // GoRoute(path: '/wiki', builder: (_, _) => const WikiScreen()),
  // GoRoute(path: '/channel', builder: (_, _) => const ChannelScreen()),
  // GoRoute(path: '/vib', builder: (_, _) => const VibScreen()),
  // GoRoute(path: '/typerank', builder: (_, _) => const TypeRankScreen()),
  // GoRoute(path: '/award', builder: (_, _) => const AwardScreen()),
  // GoRoute(path: '/bi-weekly', builder: (_, _) => const BiWeeklyScreen()),
  // GoRoute(path: '/dollars', builder: (_, _) => const DollarsScreen()),
  // GoRoute(path: '/game', builder: (_, _) => const GameScreen()),
  // GoRoute(path: '/manga', builder: (_, _) => const MangaScreen()),
  // GoRoute(path: '/hentai', builder: (_, _) => const HentaiScreen()),
  // GoRoute(path: '/nsfw', builder: (_, _) => const NsfwScreen()),
  // GoRoute(path: '/users', builder: (_, _) => const DiscoveryUsersScreen()),
  // GoRoute(path: '/adv', builder: (_, _) => const AdvScreen()),
  // GoRoute(path: '/browser', builder: (_, _) => const BrowserScreen()),
  // GoRoute(path: '/character', builder: (_, _) => const CharacterScreen()),
  // GoRoute(path: '/anitama', builder: (_, _) => const AnitamaScreen()),
  // GoRoute(path: '/wordcloud', builder: (_, _) => const WordCloudScreen()),
  // GoRoute(path: '/milestone', builder: (_, _) => const MilestoneScreen()),
];
